/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem { 'productId' : string, 'quantity' : bigint }
export type ExternalBlob = Uint8Array;
export interface Order {
  'id' : string,
  'customerName' : string,
  'status' : OrderStatus,
  'createdAt' : Time,
  'updatedAt' : Time,
  'address' : string,
  'customerId' : Principal,
  'phone' : string,
  'items' : Array<OrderItem>,
  'totalPrice' : bigint,
}
export interface OrderItem {
  'productId' : string,
  'quantity' : bigint,
  'price' : bigint,
}
export type OrderStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'delivered' : null } |
  { 'processing' : null };
export interface Product {
  'id' : string,
  'offer' : [] | [string],
  'name' : string,
  'createdAt' : Time,
  'description' : string,
  'isActive' : boolean,
  'updatedAt' : Time,
  'category' : string,
  'price' : bigint,
  'videos' : Array<ExternalBlob>,
  'images' : Array<ExternalBlob>,
}
export interface ProductStats {
  'id' : string,
  'views' : bigint,
  'wishlists' : bigint,
  'sales' : bigint,
}
export interface StoreInfo {
  'hours' : string,
  'name' : string,
  'googleMapsLink' : string,
  'contactNumber' : string,
  'rating' : number,
  'reviewCount' : bigint,
  'location' : string,
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'address' : [] | [string],
  'phone' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCategory' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<
    [string, string, string, bigint, [] | [string], string],
    undefined
  >,
  'addToWishlist' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOrder' : ActorMethod<
    [string, string, string, string, Array<CartItem>],
    undefined
  >,
  'deleteCategory' : ActorMethod<[string], undefined>,
  'getActiveOrders' : ActorMethod<[], Array<Order>>,
  'getActiveProducts' : ActorMethod<[], Array<Product>>,
  'getAllCategories' : ActorMethod<[], Array<string>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllProductStats' : ActorMethod<[], Array<ProductStats>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCompletedOrders' : ActorMethod<[], Array<Order>>,
  'getFeaturedProducts' : ActorMethod<[], Array<Product>>,
  'getMyOrders' : ActorMethod<[], Array<Order>>,
  'getOrder' : ActorMethod<[string], Order>,
  'getProduct' : ActorMethod<[string], [] | [Product]>,
  'getProductStats' : ActorMethod<[string], [] | [ProductStats]>,
  'getProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'getStoreInfo' : ActorMethod<[], StoreInfo>,
  'getSystemStats' : ActorMethod<
    [],
    {
      'totalProducts' : bigint,
      'totalOrders' : bigint,
      'pendingOrders' : bigint,
      'totalSales' : bigint,
      'activeProducts' : bigint,
    }
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWishlist' : ActorMethod<[], Array<string>>,
  'incrementProductViews' : ActorMethod<[string], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeFromWishlist' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setFeaturedProducts' : ActorMethod<[Array<string>], undefined>,
  'updateOrderStatus' : ActorMethod<[string, OrderStatus], undefined>,
  'updateProduct' : ActorMethod<
    [string, string, string, bigint, [] | [string], string, boolean],
    undefined
  >,
  'updateProductMedia' : ActorMethod<
    [string, Array<ExternalBlob>, Array<ExternalBlob>],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];