/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CartItem = IDL.Record({
  'productId' : IDL.Text,
  'quantity' : IDL.Nat,
});
export const OrderStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'delivered' : IDL.Null,
  'processing' : IDL.Null,
});
export const Time = IDL.Int;
export const OrderItem = IDL.Record({
  'productId' : IDL.Text,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : IDL.Text,
  'customerName' : IDL.Text,
  'status' : OrderStatus,
  'createdAt' : Time,
  'updatedAt' : Time,
  'address' : IDL.Text,
  'customerId' : IDL.Principal,
  'phone' : IDL.Text,
  'items' : IDL.Vec(OrderItem),
  'totalPrice' : IDL.Nat,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Product = IDL.Record({
  'id' : IDL.Text,
  'offer' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'updatedAt' : Time,
  'category' : IDL.Text,
  'price' : IDL.Nat,
  'videos' : IDL.Vec(ExternalBlob),
  'images' : IDL.Vec(ExternalBlob),
});
export const ProductStats = IDL.Record({
  'id' : IDL.Text,
  'views' : IDL.Nat,
  'wishlists' : IDL.Nat,
  'sales' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'address' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
});
export const StoreInfo = IDL.Record({
  'hours' : IDL.Text,
  'name' : IDL.Text,
  'googleMapsLink' : IDL.Text,
  'contactNumber' : IDL.Text,
  'rating' : IDL.Float64,
  'reviewCount' : IDL.Nat,
  'location' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCategory' : IDL.Func([IDL.Text], [], []),
  'addProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Opt(IDL.Text), IDL.Text],
      [],
      [],
    ),
  'addToWishlist' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createOrder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(CartItem)],
      [],
      [],
    ),
  'deleteCategory' : IDL.Func([IDL.Text], [], []),
  'getActiveOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getActiveProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAllCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllProductStats' : IDL.Func([], [IDL.Vec(ProductStats)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCompletedOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getOrder' : IDL.Func([IDL.Text], [Order], ['query']),
  'getProduct' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
  'getProductStats' : IDL.Func([IDL.Text], [IDL.Opt(ProductStats)], ['query']),
  'getProductsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'getStoreInfo' : IDL.Func([], [StoreInfo], ['query']),
  'getSystemStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalProducts' : IDL.Nat,
          'totalOrders' : IDL.Nat,
          'pendingOrders' : IDL.Nat,
          'totalSales' : IDL.Nat,
          'activeProducts' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWishlist' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'incrementProductViews' : IDL.Func([IDL.Text], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeFromWishlist' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setFeaturedProducts' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Text, OrderStatus], [], []),
  'updateProduct' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Bool,
      ],
      [],
      [],
    ),
  'updateProductMedia' : IDL.Func(
      [IDL.Text, IDL.Vec(ExternalBlob), IDL.Vec(ExternalBlob)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CartItem = IDL.Record({ 'productId' : IDL.Text, 'quantity' : IDL.Nat });
  const OrderStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'delivered' : IDL.Null,
    'processing' : IDL.Null,
  });
  const Time = IDL.Int;
  const OrderItem = IDL.Record({
    'productId' : IDL.Text,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : IDL.Text,
    'customerName' : IDL.Text,
    'status' : OrderStatus,
    'createdAt' : Time,
    'updatedAt' : Time,
    'address' : IDL.Text,
    'customerId' : IDL.Principal,
    'phone' : IDL.Text,
    'items' : IDL.Vec(OrderItem),
    'totalPrice' : IDL.Nat,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Product = IDL.Record({
    'id' : IDL.Text,
    'offer' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'updatedAt' : Time,
    'category' : IDL.Text,
    'price' : IDL.Nat,
    'videos' : IDL.Vec(ExternalBlob),
    'images' : IDL.Vec(ExternalBlob),
  });
  const ProductStats = IDL.Record({
    'id' : IDL.Text,
    'views' : IDL.Nat,
    'wishlists' : IDL.Nat,
    'sales' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'address' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
  });
  const StoreInfo = IDL.Record({
    'hours' : IDL.Text,
    'name' : IDL.Text,
    'googleMapsLink' : IDL.Text,
    'contactNumber' : IDL.Text,
    'rating' : IDL.Float64,
    'reviewCount' : IDL.Nat,
    'location' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCategory' : IDL.Func([IDL.Text], [], []),
    'addProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Opt(IDL.Text), IDL.Text],
        [],
        [],
      ),
    'addToWishlist' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createOrder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(CartItem)],
        [],
        [],
      ),
    'deleteCategory' : IDL.Func([IDL.Text], [], []),
    'getActiveOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getActiveProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAllCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllProductStats' : IDL.Func([], [IDL.Vec(ProductStats)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCompletedOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getOrder' : IDL.Func([IDL.Text], [Order], ['query']),
    'getProduct' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
    'getProductStats' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ProductStats)],
        ['query'],
      ),
    'getProductsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getStoreInfo' : IDL.Func([], [StoreInfo], ['query']),
    'getSystemStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalProducts' : IDL.Nat,
            'totalOrders' : IDL.Nat,
            'pendingOrders' : IDL.Nat,
            'totalSales' : IDL.Nat,
            'activeProducts' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWishlist' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'incrementProductViews' : IDL.Func([IDL.Text], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeFromWishlist' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setFeaturedProducts' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Text, OrderStatus], [], []),
    'updateProduct' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Bool,
        ],
        [],
        [],
      ),
    'updateProductMedia' : IDL.Func(
        [IDL.Text, IDL.Vec(ExternalBlob), IDL.Vec(ExternalBlob)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };